services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_URL=mysql+aiomysql://user:password@db:3306/salary_calculator
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:11.8-ubi9-rc
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=salary_calculator
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

volumes:
  mariadb_data: