"""add type to TaxRate

Revision ID: 4cd000f431b1
Revises: 04f47f4243eb
Create Date: 2025-03-25 20:08:28.729032

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4cd000f431b1"
down_revision: Union[str, None] = "04f47f4243eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tax_rates", sa.Column("type", sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tax_rates", "type")
    # ### end Alembic commands ###
