"""add tax exemptions

Revision ID: aef4491a4587
Revises: 4cd000f431b1
Create Date: 2025-03-25 21:55:05.296869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef4491a4587'
down_revision: Union[str, None] = '4cd000f431b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_exemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('annual_amount', sa.Float(), nullable=False),
    sa.Column('monthly_amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_exemptions_code'), 'tax_exemptions', ['code'], unique=True)
    op.create_index(op.f('ix_tax_exemptions_id'), 'tax_exemptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_exemptions_id'), table_name='tax_exemptions')
    op.drop_index(op.f('ix_tax_exemptions_code'), table_name='tax_exemptions')
    op.drop_table('tax_exemptions')
    # ### end Alembic commands ###
